//loading
export const LOADING_PAGE='LOADING_PAGE'

// HOME
export const HOME_REQUEST = 'HOME_REQUEST';
export const GET_HOME_LIST = 'GET_HOME_LIST';


export const GRID_VIEW_2 = 'GRID_VIEW_2'

export const GRID_VIEW_3 = 'GRID_VIEW_3'

// SHOW ROOM
export const SHOWROOM_REQUEST = 'SHOWROOM_REQUEST';
export const GET_SHOWROOM_LIST = 'GET_SHOWROOM_LIST';
export const GET_SHOWROOM_DETAIL = 'GET_SHOWROOM_DETAIL';
export const GET_SHOWROOM_LIST_LOADMORE = 'GET_SHOWROOM_LIST_LOADMORE'
export const GET_SEARCH_LIST_NULL = 'GET_SEARCH_LIST_NULL'

// SERVICE
export const SERVICE_REQUEST = 'SERVICE_REQUEST';
export const GET_SERVICE_LIST = 'GET_SERVICE_LIST';
export const GET_SERVICE_DETAIL = 'GET_SERVICE_DETAIL';

// BRAND
export const BRAND_REQUEST = 'BRAND_REQUEST';
export const GET_BRAND_LIST = 'GET_BRAND_LIST';
export const GET_BRAND_DETAIL = 'GET_BRAND_DETAIL';
export const GET_BRAND_LIST_LOADMORE = 'GET_BRAND_LIST_LOADMORE'
export const GET_BRAND_LIST_NULL = 'GET_BRAND_LIST_NULL'


//DESIGNER

export const DESIGNER_REQUEST = 'DESIGNER_REQUEST'
export const GET_DESIGNER_LIST = 'GET_DESIGNER_LIST'
export const GET_DESIGNER_DETAIL = 'GET_DESIGNER_DETAIL'
export const RESET_DESIGNER = 'RESET_DESIGNER'

//ABOUT
export const ABOUT_REQUEST = 'ABOUT_REQUEST'
export const GET_ABOUT_LIST = 'GET_ABOUT_LIST'
export const RESET_ABOUT = 'RESET_ABOUT'

// NEWS
export const NEWS_REQUEST = 'NEWS_REQUEST';
export const GET_NEWS_LIST = 'GET_NEWS_LIST';
export const GET_NEWS_DETAIL = 'GET_NEWS_DETAIL';

//SEARCH

export const SEARCH_TEXT = 'SEARCH_TEXT'
